#!/bin/sh

set -e

installinit_error() {
	status=$?
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/ntpd.pid && exit 0
	exit $status
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/ntp" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d ntp stop || installinit_error
	else
		/etc/init.d/ntp stop || installinit_error
	fi
fi
# End automatically added section

